baseURL: https://wello6143.github.io
languageCode: en-us
title: wello
paginate: 10
theme: PaperMod


minify:
    disableXML: true
    minifyOutput: true

params:
    title: wello
    keywords: [Blog, Portfolio, PaperMod]
    author: wello6143
    DateFormat: "Jan 02, 2006"
    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: show
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false
    defaultTheme: dark
    ShowPostNavLinks: true

    homeInfoParams:
      Title: "welcome to wello's blog"
      Content: >
                Bài viết chủ yếu về máy tính, toán và anh ngữ

    socialIcons:
      - name: twitter
        url: "https://www.twitter.com/wello6143"
      - name: hackerrank
        url: "https://www.hackerrank.com/wello6143"
      - name: github
        url: "https://www.github.com/wello6143"
      - name: linkedin
        url: "https://www.linkedin.com/in/wello6143"


menu:
  main:
      - name: Archives
        url: archive/
        weight: 5
      - name: Search
        url: search/
        weight: 7
      - name: Tags
        url: tags/
        weight: 8